---
kind: pipeline
type: docker
name: chick

clone:
  depth: 1

steps:
  - name: ci
    pull: if-not-exists
    image: golang
    commands:
      - go version
      - go env
      - go build -o oauth2 ./app/account/oauth2/cmd
