// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oauth2.proto

package oauth2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessTokenReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=ClientSecret,proto3" json:"ClientSecret,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenReq) Reset()         { *m = AccessTokenReq{} }
func (m *AccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*AccessTokenReq) ProtoMessage()    {}
func (*AccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{0}
}

func (m *AccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenReq.Unmarshal(m, b)
}
func (m *AccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenReq.Marshal(b, m, deterministic)
}
func (m *AccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenReq.Merge(m, src)
}
func (m *AccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_AccessTokenReq.Size(m)
}
func (m *AccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenReq proto.InternalMessageInfo

func (m *AccessTokenReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AccessTokenReq) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *AccessTokenReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AccessTokenReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	ExpiresIn            string   `protobuf:"bytes,2,opt,name=ExpiresIn,proto3" json:"ExpiresIn,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Openid               string   `protobuf:"bytes,4,opt,name=Openid,proto3" json:"Openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenReply) Reset()         { *m = AccessTokenReply{} }
func (m *AccessTokenReply) String() string { return proto.CompactTextString(m) }
func (*AccessTokenReply) ProtoMessage()    {}
func (*AccessTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{1}
}

func (m *AccessTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenReply.Unmarshal(m, b)
}
func (m *AccessTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenReply.Marshal(b, m, deterministic)
}
func (m *AccessTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenReply.Merge(m, src)
}
func (m *AccessTokenReply) XXX_Size() int {
	return xxx_messageInfo_AccessTokenReply.Size(m)
}
func (m *AccessTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenReply proto.InternalMessageInfo

func (m *AccessTokenReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccessTokenReply) GetExpiresIn() string {
	if m != nil {
		return m.ExpiresIn
	}
	return ""
}

func (m *AccessTokenReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AccessTokenReply) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

type VerifyTokenReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenReq) Reset()         { *m = VerifyTokenReq{} }
func (m *VerifyTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReq) ProtoMessage()    {}
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{2}
}

func (m *VerifyTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReq.Unmarshal(m, b)
}
func (m *VerifyTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReq.Merge(m, src)
}
func (m *VerifyTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReq.Size(m)
}
func (m *VerifyTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReq proto.InternalMessageInfo

func (m *VerifyTokenReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type VerifyTokenReply struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenReply) Reset()         { *m = VerifyTokenReply{} }
func (m *VerifyTokenReply) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReply) ProtoMessage()    {}
func (*VerifyTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{3}
}

func (m *VerifyTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReply.Unmarshal(m, b)
}
func (m *VerifyTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReply.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReply.Merge(m, src)
}
func (m *VerifyTokenReply) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReply.Size(m)
}
func (m *VerifyTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReply proto.InternalMessageInfo

func (m *VerifyTokenReply) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type RefreshTokenReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=ClientSecret,proto3" json:"ClientSecret,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReq) Reset()         { *m = RefreshTokenReq{} }
func (m *RefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReq) ProtoMessage()    {}
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{4}
}

func (m *RefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReq.Unmarshal(m, b)
}
func (m *RefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReq.Marshal(b, m, deterministic)
}
func (m *RefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReq.Merge(m, src)
}
func (m *RefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReq.Size(m)
}
func (m *RefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReq proto.InternalMessageInfo

func (m *RefreshTokenReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RefreshTokenReq) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *RefreshTokenReq) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenReply struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	ExpiresIn            string   `protobuf:"bytes,2,opt,name=ExpiresIn,proto3" json:"ExpiresIn,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Openid               string   `protobuf:"bytes,4,opt,name=Openid,proto3" json:"Openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReply) Reset()         { *m = RefreshTokenReply{} }
func (m *RefreshTokenReply) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReply) ProtoMessage()    {}
func (*RefreshTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{5}
}

func (m *RefreshTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReply.Unmarshal(m, b)
}
func (m *RefreshTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReply.Marshal(b, m, deterministic)
}
func (m *RefreshTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReply.Merge(m, src)
}
func (m *RefreshTokenReply) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReply.Size(m)
}
func (m *RefreshTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReply proto.InternalMessageInfo

func (m *RefreshTokenReply) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshTokenReply) GetExpiresIn() string {
	if m != nil {
		return m.ExpiresIn
	}
	return ""
}

func (m *RefreshTokenReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshTokenReply) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

type RemoveTokenReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTokenReq) Reset()         { *m = RemoveTokenReq{} }
func (m *RemoveTokenReq) String() string { return proto.CompactTextString(m) }
func (*RemoveTokenReq) ProtoMessage()    {}
func (*RemoveTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{6}
}

func (m *RemoveTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTokenReq.Unmarshal(m, b)
}
func (m *RemoveTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTokenReq.Marshal(b, m, deterministic)
}
func (m *RemoveTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTokenReq.Merge(m, src)
}
func (m *RemoveTokenReq) XXX_Size() int {
	return xxx_messageInfo_RemoveTokenReq.Size(m)
}
func (m *RemoveTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTokenReq proto.InternalMessageInfo

func (m *RemoveTokenReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type RemoveTokenReply struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTokenReply) Reset()         { *m = RemoveTokenReply{} }
func (m *RemoveTokenReply) String() string { return proto.CompactTextString(m) }
func (*RemoveTokenReply) ProtoMessage()    {}
func (*RemoveTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{7}
}

func (m *RemoveTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTokenReply.Unmarshal(m, b)
}
func (m *RemoveTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTokenReply.Marshal(b, m, deterministic)
}
func (m *RemoveTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTokenReply.Merge(m, src)
}
func (m *RemoveTokenReply) XXX_Size() int {
	return xxx_messageInfo_RemoveTokenReply.Size(m)
}
func (m *RemoveTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTokenReply proto.InternalMessageInfo

func (m *RemoveTokenReply) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func init() {
	proto.RegisterType((*AccessTokenReq)(nil), "oauth2.AccessTokenReq")
	proto.RegisterType((*AccessTokenReply)(nil), "oauth2.AccessTokenReply")
	proto.RegisterType((*VerifyTokenReq)(nil), "oauth2.VerifyTokenReq")
	proto.RegisterType((*VerifyTokenReply)(nil), "oauth2.VerifyTokenReply")
	proto.RegisterType((*RefreshTokenReq)(nil), "oauth2.RefreshTokenReq")
	proto.RegisterType((*RefreshTokenReply)(nil), "oauth2.RefreshTokenReply")
	proto.RegisterType((*RemoveTokenReq)(nil), "oauth2.RemoveTokenReq")
	proto.RegisterType((*RemoveTokenReply)(nil), "oauth2.RemoveTokenReply")
}

func init() {
	proto.RegisterFile("oauth2.proto", fileDescriptor_8d329d12d5a0c320)
}

var fileDescriptor_8d329d12d5a0c320 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x2d, 0xb5, 0x21, 0xed, 0xd8, 0xd4, 0x3a, 0x87, 0x8a, 0xc4, 0x43, 0xb3, 0x07, 0xe3, 0xa9,
	0x07, 0xfc, 0x82, 0xa6, 0x7a, 0xe0, 0x44, 0x82, 0xc6, 0xbb, 0xc2, 0x34, 0x25, 0x45, 0x16, 0x81,
	0x1a, 0xf9, 0x09, 0x3d, 0xfa, 0xbb, 0x86, 0x05, 0x81, 0x21, 0x35, 0x6a, 0xe2, 0xc1, 0xdb, 0xce,
	0x9b, 0xdd, 0x79, 0x6f, 0x1e, 0x0f, 0x18, 0xcb, 0xfb, 0x5d, 0xb6, 0xb1, 0x16, 0x71, 0x22, 0x33,
	0x89, 0x7a, 0x59, 0x09, 0x1f, 0x26, 0x4b, 0xcf, 0xa3, 0x34, 0xbd, 0x95, 0x5b, 0x8a, 0x5c, 0x7a,
	0x42, 0x13, 0x86, 0xab, 0x30, 0xa0, 0x28, 0xb3, 0x7d, 0x43, 0x9b, 0x6b, 0x17, 0x23, 0xb7, 0xae,
	0x51, 0xc0, 0xb8, 0x3c, 0xdf, 0x90, 0x97, 0x50, 0x66, 0xf4, 0x55, 0x9f, 0x61, 0x88, 0x30, 0x58,
	0x49, 0x9f, 0x8c, 0x03, 0xd5, 0x53, 0x67, 0xf1, 0xaa, 0xc1, 0x94, 0xd1, 0xc4, 0x61, 0x8e, 0x73,
	0x38, 0x6c, 0x61, 0x15, 0x57, 0x1b, 0xc2, 0x33, 0x18, 0x5d, 0xbf, 0xc4, 0x41, 0x42, 0xa9, 0x1d,
	0x55, 0x5c, 0x0d, 0x50, 0x88, 0x71, 0x69, 0x9d, 0x50, 0xba, 0x29, 0x07, 0x94, 0x84, 0x0c, 0xc3,
	0x19, 0xe8, 0x4e, 0x4c, 0x51, 0xe0, 0x1b, 0x03, 0xd5, 0xad, 0x2a, 0x61, 0xc1, 0xe4, 0x8e, 0x92,
	0x60, 0x9d, 0xd7, 0x6b, 0x7f, 0xab, 0x46, 0x9c, 0xc3, 0x94, 0xbd, 0x29, 0x76, 0x40, 0x18, 0xd8,
	0xa9, 0xb3, 0x55, 0xd7, 0x87, 0xae, 0x3a, 0x8b, 0x1d, 0x1c, 0xb5, 0x35, 0xfc, 0x85, 0xa7, 0x3f,
	0x58, 0x55, 0xbc, 0x69, 0x70, 0xcc, 0x79, 0xff, 0x81, 0xc9, 0x2e, 0x3d, 0xca, 0x67, 0xfa, 0x9d,
	0xc9, 0xec, 0xcd, 0x17, 0x26, 0x5b, 0xef, 0x7d, 0xd0, 0x1d, 0x15, 0x61, 0x5c, 0xb2, 0xa1, 0x38,
	0x5b, 0x54, 0x41, 0xe7, 0xb9, 0x36, 0x8d, 0xbd, 0x78, 0x1c, 0xe6, 0xa2, 0x57, 0x8c, 0x68, 0x7d,
	0xda, 0x66, 0x04, 0xcf, 0x48, 0x33, 0xa2, 0x9b, 0x03, 0xd1, 0xc3, 0x2b, 0x6e, 0x14, 0x9e, 0x7c,
	0xde, 0xed, 0x64, 0xc1, 0x3c, 0xdd, 0xdf, 0xa8, 0x85, 0xb4, 0xd6, 0x6f, 0x84, 0x70, 0x1f, 0x1b,
	0x21, 0x5d, 0xaf, 0x44, 0xef, 0x41, 0x57, 0x3f, 0xf8, 0xe5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x00, 0xb3, 0x19, 0xc3, 0xf0, 0x03, 0x00, 0x00,
}
