// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oauth2.proto

package oauth2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessTokenReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenReq) Reset()         { *m = AccessTokenReq{} }
func (m *AccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*AccessTokenReq) ProtoMessage()    {}
func (*AccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{0}
}

func (m *AccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenReq.Unmarshal(m, b)
}
func (m *AccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenReq.Marshal(b, m, deterministic)
}
func (m *AccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenReq.Merge(m, src)
}
func (m *AccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_AccessTokenReq.Size(m)
}
func (m *AccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenReq proto.InternalMessageInfo

type AccessTokenReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenReply) Reset()         { *m = AccessTokenReply{} }
func (m *AccessTokenReply) String() string { return proto.CompactTextString(m) }
func (*AccessTokenReply) ProtoMessage()    {}
func (*AccessTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{1}
}

func (m *AccessTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenReply.Unmarshal(m, b)
}
func (m *AccessTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenReply.Marshal(b, m, deterministic)
}
func (m *AccessTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenReply.Merge(m, src)
}
func (m *AccessTokenReply) XXX_Size() int {
	return xxx_messageInfo_AccessTokenReply.Size(m)
}
func (m *AccessTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenReply proto.InternalMessageInfo

type UserReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{2}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

type UserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReply) Reset()         { *m = UserReply{} }
func (m *UserReply) String() string { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()    {}
func (*UserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{3}
}

func (m *UserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReply.Unmarshal(m, b)
}
func (m *UserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReply.Marshal(b, m, deterministic)
}
func (m *UserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReply.Merge(m, src)
}
func (m *UserReply) XXX_Size() int {
	return xxx_messageInfo_UserReply.Size(m)
}
func (m *UserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserReply proto.InternalMessageInfo

type UserOpenIDReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOpenIDReq) Reset()         { *m = UserOpenIDReq{} }
func (m *UserOpenIDReq) String() string { return proto.CompactTextString(m) }
func (*UserOpenIDReq) ProtoMessage()    {}
func (*UserOpenIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{4}
}

func (m *UserOpenIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOpenIDReq.Unmarshal(m, b)
}
func (m *UserOpenIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOpenIDReq.Marshal(b, m, deterministic)
}
func (m *UserOpenIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOpenIDReq.Merge(m, src)
}
func (m *UserOpenIDReq) XXX_Size() int {
	return xxx_messageInfo_UserOpenIDReq.Size(m)
}
func (m *UserOpenIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOpenIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserOpenIDReq proto.InternalMessageInfo

type UserOpenIDReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOpenIDReply) Reset()         { *m = UserOpenIDReply{} }
func (m *UserOpenIDReply) String() string { return proto.CompactTextString(m) }
func (*UserOpenIDReply) ProtoMessage()    {}
func (*UserOpenIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d329d12d5a0c320, []int{5}
}

func (m *UserOpenIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOpenIDReply.Unmarshal(m, b)
}
func (m *UserOpenIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOpenIDReply.Marshal(b, m, deterministic)
}
func (m *UserOpenIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOpenIDReply.Merge(m, src)
}
func (m *UserOpenIDReply) XXX_Size() int {
	return xxx_messageInfo_UserOpenIDReply.Size(m)
}
func (m *UserOpenIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOpenIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserOpenIDReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccessTokenReq)(nil), "micro.service.oauth2.AccessTokenReq")
	proto.RegisterType((*AccessTokenReply)(nil), "micro.service.oauth2.AccessTokenReply")
	proto.RegisterType((*UserReq)(nil), "micro.service.oauth2.UserReq")
	proto.RegisterType((*UserReply)(nil), "micro.service.oauth2.UserReply")
	proto.RegisterType((*UserOpenIDReq)(nil), "micro.service.oauth2.UserOpenIDReq")
	proto.RegisterType((*UserOpenIDReply)(nil), "micro.service.oauth2.UserOpenIDReply")
}

func init() {
	proto.RegisterFile("oauth2.proto", fileDescriptor_8d329d12d5a0c320)
}

var fileDescriptor_8d329d12d5a0c320 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4f, 0x2c, 0x2d,
	0xc9, 0x30, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc9, 0xcd, 0x4c, 0x2e, 0xca, 0xd7,
	0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x83, 0xc8, 0x29, 0x09, 0x70, 0xf1, 0x39, 0x26,
	0x27, 0xa7, 0x16, 0x17, 0x87, 0xe4, 0x67, 0xa7, 0xe6, 0x05, 0xa5, 0x16, 0x2a, 0x09, 0x71, 0x09,
	0xa0, 0x88, 0x14, 0xe4, 0x54, 0x2a, 0x71, 0x72, 0xb1, 0x87, 0x16, 0xa7, 0x16, 0x81, 0xa4, 0xb9,
	0xb9, 0x38, 0x21, 0x4c, 0x90, 0x38, 0x3f, 0x17, 0x2f, 0x88, 0xe3, 0x5f, 0x90, 0x9a, 0xe7, 0xe9,
	0x02, 0x92, 0x15, 0xe4, 0xe2, 0x47, 0x16, 0x28, 0xc8, 0xa9, 0x34, 0xea, 0x65, 0xe2, 0x62, 0xf3,
	0x07, 0x5b, 0x26, 0x14, 0xcb, 0xc5, 0x8d, 0x64, 0xb4, 0x90, 0x8a, 0x1e, 0x36, 0x27, 0xe9, 0xa1,
	0xba, 0x47, 0x4a, 0x8d, 0x08, 0x55, 0x20, 0xb7, 0x30, 0x08, 0x79, 0x70, 0xb1, 0x80, 0x2c, 0x17,
	0x92, 0xc5, 0xae, 0x03, 0xea, 0x03, 0x29, 0x79, 0x7c, 0xd2, 0x10, 0x93, 0xa2, 0xb8, 0xb8, 0x10,
	0xde, 0x10, 0x52, 0xc6, 0xad, 0x01, 0xee, 0x73, 0x29, 0x55, 0xc2, 0x8a, 0xc0, 0x66, 0x3b, 0x71,
	0x44, 0xb1, 0x41, 0xe4, 0x92, 0xd8, 0xc0, 0x11, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x53,
	0xb2, 0x05, 0x67, 0xa8, 0x01, 0x00, 0x00,
}
