// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: oauth2.proto

package oauth2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Oauth2 service

type Oauth2Service interface {
	AccessToken(ctx context.Context, in *AccessTokenReq, opts ...client.CallOption) (*AccessTokenReply, error)
	User(ctx context.Context, in *UserReq, opts ...client.CallOption) (*UserReply, error)
	UserOpenID(ctx context.Context, in *UserOpenIDReq, opts ...client.CallOption) (*UserOpenIDReply, error)
}

type oauth2Service struct {
	c    client.Client
	name string
}

func NewOauth2Service(name string, c client.Client) Oauth2Service {
	return &oauth2Service{
		c:    c,
		name: name,
	}
}

func (c *oauth2Service) AccessToken(ctx context.Context, in *AccessTokenReq, opts ...client.CallOption) (*AccessTokenReply, error) {
	req := c.c.NewRequest(c.name, "Oauth2.AccessToken", in)
	out := new(AccessTokenReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2Service) User(ctx context.Context, in *UserReq, opts ...client.CallOption) (*UserReply, error) {
	req := c.c.NewRequest(c.name, "Oauth2.User", in)
	out := new(UserReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2Service) UserOpenID(ctx context.Context, in *UserOpenIDReq, opts ...client.CallOption) (*UserOpenIDReply, error) {
	req := c.c.NewRequest(c.name, "Oauth2.UserOpenID", in)
	out := new(UserOpenIDReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Oauth2 service

type Oauth2Handler interface {
	AccessToken(context.Context, *AccessTokenReq, *AccessTokenReply) error
	User(context.Context, *UserReq, *UserReply) error
	UserOpenID(context.Context, *UserOpenIDReq, *UserOpenIDReply) error
}

func RegisterOauth2Handler(s server.Server, hdlr Oauth2Handler, opts ...server.HandlerOption) error {
	type oauth2 interface {
		AccessToken(ctx context.Context, in *AccessTokenReq, out *AccessTokenReply) error
		User(ctx context.Context, in *UserReq, out *UserReply) error
		UserOpenID(ctx context.Context, in *UserOpenIDReq, out *UserOpenIDReply) error
	}
	type Oauth2 struct {
		oauth2
	}
	h := &oauth2Handler{hdlr}
	return s.Handle(s.NewHandler(&Oauth2{h}, opts...))
}

type oauth2Handler struct {
	Oauth2Handler
}

func (h *oauth2Handler) AccessToken(ctx context.Context, in *AccessTokenReq, out *AccessTokenReply) error {
	return h.Oauth2Handler.AccessToken(ctx, in, out)
}

func (h *oauth2Handler) User(ctx context.Context, in *UserReq, out *UserReply) error {
	return h.Oauth2Handler.User(ctx, in, out)
}

func (h *oauth2Handler) UserOpenID(ctx context.Context, in *UserOpenIDReq, out *UserOpenIDReply) error {
	return h.Oauth2Handler.UserOpenID(ctx, in, out)
}
